services:
  b9-printer-mgmt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b9-printer-mgmt
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8004:8000"
    command: >
      python manage.py runserver 0.0.0.0:8000
    # gunicorn  --bind 0.0.0.0:8000 
    #           --workers 3 
    #           --timeout 60 
    #           b9_printer_mgmt.wsgi:application

